# GNU/Linux makefile for GLICT
# GNU LGPLv2 (or any later version at your opinion) applies to this file as 
# well.
CPPFLAGS = -I../
CXX = g++

all: 
	cd GLICT
	make all

libGLICT.a: 
	cd GLICT
	make libGLICT.a	
	
#g++ $(OBJS) -o libglict.a  -lGL 
clean:
	cd GLICT
	make clean

install:
	cd GLICT
	make install
