Document: glict
Title: Debian glict Manual
Author: <insert document author here>
Abstract: This manual describes what glict is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glict/glict.sgml.gz

Format: postscript
Files: /usr/share/doc/glict/glict.ps.gz

Format: text
Files: /usr/share/doc/glict/glict.text.gz

Format: HTML
Index: /usr/share/doc/glict/html/index.html
Files: /usr/share/doc/glict/html/*.html


